apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          env:
            - name: ENVIRONMENT
              value: prod
